task:
  timeout_in: 120m
  freebsd_instance:
    image_family: freebsd-15-0-snap
    cpu: 8
    memory: 32G

  Pre-Build_script:
    - |
      sed -i /usr/local/etc/pkg.conf \
          -e 's/#DEFAULT_ALWAYS_YES = false;/DEFAULT_ALWAYS_YES = true;/'
          -e 's/#ASSUME_ALWAYS_YES = false;/ASSUME_ALWAYS_YES = true;/'
    - sudo pkg update
    - sudo pkg upgrade
    - >-
      sudo pkg install automake autoconf binutils
      gcc gmp mpc mpfr isl libtool intltool
