task:
  timeout_in: 120m
  resources:
    cpu: 8
    memory: 32G
  freebsd-instance:
    image-family: freebsd-15
  env:
    ASSUME_ALWAYS_YES: yes

  Pre-Build_script:
    - sudo pkg update
    - sudo pkg upgrade
    - >-
      sudo pkg install -y automake autoconf binutils
      gcc gmp mpc mpfr isl libtool intltool
