task:
  timeout_in: 120m
  freebsd_instance:
    image_family: freebsd-15-0-snap
    cpu: 8
    memory: 32G

  Pre-Build_script:
    - cat /usr/local/etc/pkg.conf
    - sudo pkg update
    - sudo pkg upgrade
    - >-
      sudo pkg install automake autoconf binutils
      gcc gmp mpc mpfr isl libtool intltool
