task:
  timeout_in: 120m
  freebsd_instance:
    image_family: freebsd-15-0-snap
    cpu: 8
    memory: 32G

  Pre-Build_script:
    - sed -i 's|#DEFAULT_ALWAYS_YES = false|DEFAULT_ALWAYS_YES = true|' /usr/local/etc/pkg.conf
    - sed -i 's|#ASSUME_ALWAYS_YES = false|ASSUME_ALWAYS_YES = true|' /usr/local/etc/pkg.conf
    - sudo pkg update
    - sudo pkg upgrade
    - sudo pkg install automake autoconf binutils gcc gmp mpc mpfr isl libtool intltool
