name: Build

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build
        run: docker build .
