name: Build

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build
        run: |
          ./fetch.sh
          docker build . -t freebsd-docker-builder
          docker run --rm -i freebsd-docker-builder bash <<SH
          echo hi
          SH
