name: Build

on:
  push:
    branches:
      - main

env:
  FREEBSD_VERSION: '15.0'

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build
        run: |
          ./fetch.sh
          docker build . -t freebsd-docker-builder
