name: Build

on:
  push:
    branches:
      - main

env:
  FREEBSD_VERSION: 15.0

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build
        run: |
          wget -q "https://download.freebsd.org/snapshots/amd64/${{ env.FREEBSD_VERSION }}-CURRENT/base.txz"
          wget -q "https://download.freebsd.org/snapshots/amd64/${{ env.FREEBSD_VERSION }}-CURRENT/lib32.txz"
          docker build .
